// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8080' | (string & {});
};

export type SessionToken = {
    accessToken?: string;
    expiresAt?: string;
    principalId?: string;
    cartId?: string;
};

export type RunSnapshot = {
    id?: string;
    conversationId?: string;
    status?: string;
    epoch?: string;
    sequence?: string;
    text?: string;
    errorCode?: string | unknown;
    createdAt?: string;
    finishedAt?: string | unknown;
};

export type Conversation = {
    id?: string;
    version?: string;
    createdAt?: string;
};

export type TurnRequest = {
    text?: string;
    resultSetId?: string;
    expectedStateVersion?: string;
};

export type AcceptedTurn = {
    messageId?: string;
    runId?: string;
};

export type Accepted = {
    attachmentId?: string;
    jobId?: string;
    version?: string;
    status?: string;
    deduplicated?: boolean;
};

export type SearchCriteria = {
    query?: string;
    limit?: number;
    category?: string;
    brand?: string;
    minPrice?: string;
    maxPrice?: string;
    currency?: string;
    specs?: {
        [key: string]: string;
    };
    exactArticle?: boolean;
};

export type Money = {
    amount?: string;
    currency?: string;
};

export type OfferSnapshot = {
    article?: string;
    price?: Money;
    available?: Quantity;
    warehouse?: string;
    stockBucket?: string;
    version?: string;
    observedAt?: string;
    expiresAt?: string;
};

export type ProductDetails = {
    id?: string;
    article?: string;
    name?: string;
    specs?: {
        [key: string]: string;
    };
    certificates?: Array<SourceRef>;
};

export type ProductResultSet = {
    id?: string;
    version?: string;
    products?: Array<ProductDetails>;
    offers?: Array<OfferSnapshot>;
};

export type Quantity = {
    value?: string;
    unit?: string;
    step?: string;
};

export type SavedSearch = {
    resultSet?: ProductResultSet;
    appliedConstraints?: SearchCriteria;
    mode?: string;
    warnings?: Array<string>;
};

export type SourceRef = {
    id?: string;
    version?: string;
    title?: string;
    page?: number | unknown;
    sheet?: string | unknown;
    row?: number | unknown;
};

export type CompareRequest = {
    indices?: Array<number>;
};

export type ProposalRequest = {
    conversationId: string;
    expectedStateVersion?: string;
    resultSetId?: string;
    lines?: Array<Selection>;
};

export type Selection = {
    article?: string;
    unit?: string;
    warehouse?: string;
    addQuantity?: string;
};

export type ProposalLine = {
    article?: string;
    addQuantity?: Quantity;
    unitPrice?: Money;
    warehouse?: string;
    stockBucket?: string;
    offerVersion?: string;
    provenance?: Array<string>;
};

export type ProposalSnapshot = {
    id?: string;
    conversationId?: string;
    cartId?: string;
    revision?: string;
    digest?: string;
    operationId?: string;
    expectedCartVersion?: string;
    status?: string;
    expiresAt?: string;
    lines?: Array<ProposalLine>;
};

export type ConfirmRequest = {
    revision?: string;
    digest?: string;
    origin: 'button' | 'user_text';
    text?: string;
};

export type CartLine = {
    article?: string;
    quantity?: Quantity;
    unitPrice?: Money;
    warehouse?: string;
    stockBucket?: string;
};

export type CartSnapshot = {
    id?: string;
    version?: string;
    lines?: Array<CartLine>;
    url?: string;
};

export type OperationOutcome = {
    id?: string;
    proposalId?: string;
    status?: string;
    cart?: CartSnapshot | unknown;
    code?: string | unknown;
};

export type AttachmentSelection = {
    rowId?: string;
    productId?: string;
    quantity?: string;
    unit?: string;
    warehouse?: string;
    selected?: boolean;
};

export type ReviewRequest = {
    expectedVersion?: string;
    selections: Array<AttachmentSelection>;
};

export type Candidate = {
    productId?: string;
    article?: string;
    name?: string;
    unit?: string;
    evidence?: string;
    minimum?: string;
    step?: string;
    warehouses?: Array<string>;
};

export type ExtractedRow = {
    id?: string;
    rawText?: string;
    article?: string;
    quantity?: string;
    unit?: string;
    source?: Location;
    warnings?: Array<string>;
    visualEvidence?: VisualEvidence;
};

export type Location = {
    kind?: string;
    sheet?: string;
    row?: number;
    cell?: string;
    page?: number;
    paragraph?: number;
    words?: Array<WordBox>;
};

export type MatchedRow = {
    extracted?: ExtractedRow;
    status?: string;
    candidates?: Array<Candidate>;
};

export type Snapshot = {
    attachmentId?: string;
    conversationId?: string;
    version?: string;
    status?: string;
    stage?: string;
    filename?: string;
    mimeType?: string;
    rows?: Array<MatchedRow>;
    selections?: Array<AttachmentSelection>;
    warnings?: Array<string>;
    errorCode?: string;
};

export type VisualEvidence = {
    category?: string;
    visibleMarkings?: Array<string>;
    observedAttributes?: {
        [key: string]: string;
    };
    qualityFlags?: Array<string>;
};

export type WordBox = {
    text?: string;
    x?: number;
    y?: number;
    width?: number;
    height?: number;
    imageWidth?: number;
    imageHeight?: number;
    confidence?: number;
    lineId?: string;
};

export type ReprocessRequest = {
    expectedVersion?: string;
};

export type ImportRequest = {
    externalId?: string;
    title?: string;
    version?: string;
    visibility: 'PUBLIC' | 'PRIVATE';
    sourceUrl?: string;
    text?: string;
    tags: Array<string>;
    synthetic?: boolean;
    semanticIndex?: boolean;
};

export type Job = {
    id?: string;
    documentId?: string;
    versionId?: string;
    state?: string;
    errorCode?: string;
    epoch?: string;
};

/**
 * Документ импорта каталога
 */
export type CatalogImportRequest = {
    schemaVersion: number;
    synthetic?: boolean;
    /**
     * Версия выгрузки источника
     */
    version?: string;
    products?: Array<ProductRequest>;
};

export type CertificateRequest = {
    id?: string;
    url?: string;
    file?: string;
    version?: string;
    synthetic?: boolean;
};

/**
 * Товар выгрузки. id — стабильный ID поставщика, не PK нашей БД
 */
export type ProductRequest = {
    id?: string;
    article?: string;
    name?: string;
    brand?: string;
    category?: string;
    unit?: string;
    /**
     * Минимальная партия
     */
    minimum?: number;
    /**
     * Шаг количества
     */
    step?: number;
    price?: number;
    currency?: string;
    specs?: {
        [key: string]: string;
    };
    certificates?: Array<CertificateRequest>;
    sourceUrl?: string;
    sourceVersion?: string;
    synthetic?: boolean;
    warehouses?: Array<WarehouseRequest>;
};

/**
 * Остаток на складе; количество обязательно только для точных статусов
 */
export type WarehouseRequest = {
    warehouseId?: string;
    availableQuantity?: number;
    status?: 'IN_STOCK' | 'OUT_OF_STOCK' | 'ON_ORDER' | 'UNKNOWN';
    eligible?: boolean;
};

/**
 * Ошибка или замечание импорта со стабильным кодом и путём до поля
 */
export type ImportIssueResponse = {
    code?: string;
    path?: string;
    message?: string;
};

/**
 * Состояние задания импорта каталога
 */
export type ImportJobResponse = {
    id?: string;
    jobType?: string;
    status?: 'PENDING' | 'RUNNING' | 'SUCCEEDED' | 'FAILED';
    sourceVersion?: string;
    requestedBy?: string;
    vectorSpace?: string;
    catalogVersionId?: string;
    catalogVersionStatus?: string;
    embeddingStatus?: string;
    totalProducts?: number;
    importedProducts?: number;
    embeddedProducts?: number;
    errors?: Array<ImportIssueResponse>;
    warnings?: Array<ImportIssueResponse>;
    createdAt?: string;
    startedAt?: string;
    finishedAt?: string;
};

export type UpdateDialogue = {
    expectedVersion?: string;
    category?: string;
    budget?: Money;
    hardConstraints?: {
        [key: string]: string;
    };
    quantity?: Quantity;
    resultSetId?: string;
    selectedIndices?: Array<number>;
    fulfillmentOptionId?: string;
    attachmentId?: string;
    attachmentVersion?: string;
    /**
     * Parameters to reset. Omitted fields otherwise retain their saved value. Allowed: category, budget, quantity, hardConstraints.
     */
    clearFields?: Array<string>;
};

export type DialogueState = {
    version?: string;
    category?: string | unknown;
    budget?: Money | unknown;
    hardConstraints?: {
        [key: string]: string;
    };
    quantity?: Quantity | unknown;
    lastResultSetId?: string | unknown;
    selectedArticles?: Array<string>;
    fulfillmentOptionId?: string | unknown;
    activeProposalId?: string | unknown;
    attachmentId?: string | unknown;
    attachmentVersion?: string | unknown;
};

export type UpdateOffer = {
    price?: string;
    available?: string;
    expectedVersion?: string;
};

export type Quote = {
    article?: string;
    warehouse?: string;
    status?: string;
    freshness?: string;
    error?: string;
    offer?: OfferSnapshot;
};

export type Usage = {
    epoch?: string;
    round?: number;
    model?: string;
    inputTokens?: number;
    outputTokens?: number;
    measured?: boolean;
    promptVersion?: string;
};

export type AlternativePlan = {
    id?: string;
    kind?: string;
    lines?: Array<Selection>;
    differences?: Array<string>;
};

export type AlternativesPayload = {
    alternatives?: Array<AlternativePlan>;
    kind: 'alternatives';
};

export type ChatEvent = {
    eventId?: string;
    runId?: string;
    seq?: string;
    epoch?: string;
    type?: string;
    schemaVersion?: string;
    payload?: EventPayload;
};

export type DeltaPayload = {
    text?: string;
    kind: 'delta';
};

export type EventPayload = (({
    kind: 'status';
} & StatusPayload) | ({
    kind: 'delta';
} & DeltaPayload) | ({
    kind: 'products';
} & ProductsPayload) | ({
    kind: 'proposal';
} & ProposalPayload) | ({
    kind: 'terminal';
} & TerminalPayload) | ({
    kind: 'sources';
} & SourcesPayload) | ({
    kind: 'alternatives';
} & AlternativesPayload) | ({
    kind: 'review';
} & ReviewPayload)) & {
    kind: string;
};

export type ProductsPayload = {
    resultSet?: ProductResultSet;
    kind: 'products';
};

export type ProposalPayload = {
    proposal?: ProposalSnapshot;
    kind: 'proposal';
};

export type ReviewPayload = {
    review?: ReviewedItems;
    kind: 'review';
};

export type ReviewedItems = {
    attachmentId?: string;
    version?: string;
    items?: Array<Selection>;
    sources?: Array<SourceRef>;
};

export type SourceChunk = {
    source?: SourceRef;
    text?: string;
};

export type SourcesPayload = {
    sources?: Array<SourceRef>;
    excerpts?: Array<SourceChunk>;
    kind: 'sources';
};

export type StatusPayload = {
    status?: string;
    tool?: string | unknown;
    kind: 'status';
};

export type TerminalPayload = {
    snapshot?: RunSnapshot;
    replayUnavailable?: boolean;
    kind: 'terminal';
};

export type CertificateResponse = {
    id?: string;
    url?: string;
    version?: string;
    synthetic?: boolean;
};

/**
 * Цена товара. UNKNOWN — цена неизвестна, это не ноль
 */
export type OfferResponse = {
    price?: string;
    currency?: string;
    status?: 'KNOWN' | 'UNKNOWN';
    sourceVersion?: string;
    observedAt?: string;
};

/**
 * Товар активной версии каталога
 */
export type ProductResponse = {
    /**
     * Стабильный ID товара
     */
    id?: string;
    /**
     * ID поставщика, если он известен
     */
    supplierId?: string;
    /**
     * Артикул как в источнике
     */
    article?: string;
    name?: string;
    brand?: string;
    category?: string;
    /**
     * Единица измерения
     */
    unit?: string;
    /**
     * Минимальная партия
     */
    minimumQuantity?: string;
    /**
     * Шаг количества
     */
    stepQuantity?: string;
    specs?: {
        [key: string]: string;
    };
    certificates?: Array<CertificateResponse>;
    sourceUrl?: string;
    /**
     * Версия данных источника
     */
    sourceVersion?: string;
    /**
     * Синтетические данные, а не ассортимент партнёра
     */
    synthetic?: boolean;
    catalogVersionId?: string;
    offer?: OfferResponse;
    stock?: StockResponse;
    /**
     * Близость к запросу; только для поиска
     */
    score?: number;
};

/**
 * Сводный остаток. Склады не суммируются без политики отгрузки
 */
export type StockResponse = {
    status?: 'IN_STOCK' | 'OUT_OF_STOCK' | 'ON_ORDER' | 'UNKNOWN';
    /**
     * Доступное количество; null, когда оно неизвестно
     */
    availableQuantity?: string;
    /**
     * Почему количество есть или отсутствует
     */
    quantityBasis?: 'SINGLE_WAREHOUSE' | 'MULTIPLE_WAREHOUSES_NOT_MERGED' | 'UNKNOWN' | 'NO_ELIGIBLE_WAREHOUSE';
    warehouses?: Array<WarehouseResponse>;
};

/**
 * Остаток на складе; eligible=false — отгрузка с него невозможна
 */
export type WarehouseResponse = {
    warehouseId?: string;
    status?: string;
    availableQuantity?: string;
    eligible?: boolean;
    observedAt?: string;
};

export type Analog = {
    article?: string;
    name?: string;
    compatibility?: Verdict;
    offers?: Array<Quote>;
};

export type Option = {
    id?: string;
    kind?: string;
    lines?: Array<Selection>;
    differences?: Array<string>;
    offers?: Array<OfferSnapshot>;
    version?: string;
};

export type Result = {
    originalArticle?: string;
    status?: string;
    ruleVersion?: string;
    analogs?: Array<Analog>;
    options?: Array<Option>;
    reasons?: Array<string>;
};

export type Verdict = {
    status?: string;
    matchedRequirements?: {
        [key: string]: string;
    };
    differences?: {
        [key: string]: string;
    };
    missingRequirements?: Array<string>;
};

/**
 * Результат поиска вместе с версией каталога, по которой он получен
 */
export type ProductSearchResponse = {
    catalogVersionId?: string;
    sourceVersion?: string;
    vectorSpace?: string;
    total?: number;
    items?: Array<ProductResponse>;
    mode?: string;
    warnings?: Array<string>;
};

export type PingResponse = {
    app?: string;
    status?: string;
    time?: string;
};

export type KnowledgeChunk = {
    citationId?: string;
    documentId?: string;
    versionId?: string;
    sourceKey?: string;
    title?: string;
    versionLabel?: string;
    page?: number;
    heading?: string;
    text?: string;
    sourcePath?: string;
    sha256?: string;
    synthetic?: boolean;
    untrusted?: boolean;
    score?: number;
};

export type KnowledgeSearchResult = {
    retrievalId?: string;
    answerability?: 'ANSWERABLE' | 'NO_ANSWER' | 'CONFLICT' | 'SOURCE_UNAVAILABLE' | 'CATALOG_REQUIRED';
    explanation?: string;
    retrievalMode?: string;
    chunks?: Array<KnowledgeChunk>;
    citationAllowlist?: Array<string>;
};

export type ConversationPage = {
    items?: Array<Conversation>;
    nextCursor?: string | unknown;
};

export type Message = {
    id?: string;
    sequence?: string;
    role?: string;
    text?: string;
    runId?: string;
    createdAt?: string;
};

export type MessagePage = {
    items?: Array<Message>;
    nextCursor?: string | unknown;
};

export type Capabilities = {
    extensions?: Array<string>;
    maxBytes?: number;
    maxRows?: number;
    maxPages?: number;
    maxImagePixels?: number;
    ocrAvailable?: boolean;
    visionAvailable?: boolean;
    conversationAccessConfigured?: boolean;
};

export type ApiProblem = {
    status?: unknown;
    detail?: unknown;
    code?: unknown;
    correlationId?: unknown;
    retryable?: unknown;
};

export type VisitorData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/visitor-session';
};

export type VisitorErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type VisitorError = VisitorErrors[keyof VisitorErrors];

export type VisitorResponses = {
    /**
     * OK
     */
    200: SessionToken;
};

export type VisitorResponse = VisitorResponses[keyof VisitorResponses];

export type RefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
    /**
     * OK
     */
    200: SessionToken;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CancelRunData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/runs/{id}/cancel';
};

export type CancelRunErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type CancelRunError = CancelRunErrors[keyof CancelRunErrors];

export type CancelRunResponses = {
    /**
     * OK
     */
    200: RunSnapshot;
};

export type CancelRunResponse = CancelRunResponses[keyof CancelRunResponses];

export type ListConversationsData = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/api/conversations';
};

export type ListConversationsErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type ListConversationsError = ListConversationsErrors[keyof ListConversationsErrors];

export type ListConversationsResponses = {
    /**
     * OK
     */
    200: ConversationPage;
};

export type ListConversationsResponse = ListConversationsResponses[keyof ListConversationsResponses];

export type CreateConversationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/conversations';
};

export type CreateConversationErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type CreateConversationError = CreateConversationErrors[keyof CreateConversationErrors];

export type CreateConversationResponses = {
    /**
     * Created
     */
    201: Conversation;
};

export type CreateConversationResponse = CreateConversationResponses[keyof CreateConversationResponses];

export type ListMessagesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/api/conversations/{id}/messages';
};

export type ListMessagesErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type ListMessagesError = ListMessagesErrors[keyof ListMessagesErrors];

export type ListMessagesResponses = {
    /**
     * OK
     */
    200: MessagePage;
};

export type ListMessagesResponse = ListMessagesResponses[keyof ListMessagesResponses];

export type SubmitMessageData = {
    body: TurnRequest;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/conversations/{id}/messages';
};

export type SubmitMessageErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type SubmitMessageError = SubmitMessageErrors[keyof SubmitMessageErrors];

export type SubmitMessageResponses = {
    /**
     * Accepted
     */
    202: AcceptedTurn;
};

export type SubmitMessageResponse = SubmitMessageResponses[keyof SubmitMessageResponses];

export type UploadData = {
    body?: {
        file: Blob | File;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/conversations/{id}/attachments';
};

export type UploadErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type UploadError = UploadErrors[keyof UploadErrors];

export type UploadResponses = {
    /**
     * Accepted
     */
    202: Accepted;
};

export type UploadResponse = UploadResponses[keyof UploadResponses];

export type SearchData = {
    body?: never;
    path?: never;
    query: {
        q: string;
        limit?: number;
        category?: string;
        brand?: string;
        minPrice?: number;
        maxPrice?: number;
        exactArticle?: boolean;
    };
    url: '/api/catalog/search';
};

export type SearchErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type SearchError = SearchErrors[keyof SearchErrors];

export type SearchResponses = {
    /**
     * OK
     */
    200: SavedSearch;
};

export type SearchResponse = SearchResponses[keyof SearchResponses];

export type Search1Data = {
    body: SearchCriteria;
    path?: never;
    query?: never;
    url: '/api/catalog/search';
};

export type Search1Errors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type Search1Error = Search1Errors[keyof Search1Errors];

export type Search1Responses = {
    /**
     * OK
     */
    200: SavedSearch;
};

export type Search1Response = Search1Responses[keyof Search1Responses];

export type CompareData = {
    body: CompareRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/catalog/results/{id}/compare';
};

export type CompareErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type CompareError = CompareErrors[keyof CompareErrors];

export type CompareResponses = {
    /**
     * OK
     */
    200: SavedSearch;
};

export type CompareResponse = CompareResponses[keyof CompareResponses];

export type PrepareProposalData = {
    body: ProposalRequest;
    headers: {
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/api/cart/proposals';
};

export type PrepareProposalErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type PrepareProposalError = PrepareProposalErrors[keyof PrepareProposalErrors];

export type PrepareProposalResponses = {
    /**
     * OK
     */
    200: ProposalSnapshot;
};

export type PrepareProposalResponse = PrepareProposalResponses[keyof PrepareProposalResponses];

export type RejectProposalData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/cart/proposals/{id}/reject';
};

export type RejectProposalErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type RejectProposalError = RejectProposalErrors[keyof RejectProposalErrors];

export type RejectProposalResponses = {
    /**
     * OK
     */
    200: ProposalSnapshot;
};

export type RejectProposalResponse = RejectProposalResponses[keyof RejectProposalResponses];

export type ConfirmProposalData = {
    body: ConfirmRequest;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/cart/proposals/{id}/confirm';
};

export type ConfirmProposalErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type ConfirmProposalError = ConfirmProposalErrors[keyof ConfirmProposalErrors];

export type ConfirmProposalResponses = {
    /**
     * OK
     */
    200: OperationOutcome;
};

export type ConfirmProposalResponse = ConfirmProposalResponses[keyof ConfirmProposalResponses];

export type ReviewData = {
    body: ReviewRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/attachments/{id}/review';
};

export type ReviewErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type ReviewError = ReviewErrors[keyof ReviewErrors];

export type ReviewResponses = {
    /**
     * OK
     */
    200: Snapshot;
};

export type ReviewResponse = ReviewResponses[keyof ReviewResponses];

export type ReprocessData = {
    body: ReprocessRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/attachments/{id}/reprocess';
};

export type ReprocessErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type ReprocessError = ReprocessErrors[keyof ReprocessErrors];

export type ReprocessResponses = {
    /**
     * Accepted
     */
    202: Accepted;
};

export type ReprocessResponse = ReprocessResponses[keyof ReprocessResponses];

export type IngestData = {
    body: ImportRequest;
    path?: never;
    query?: never;
    url: '/api/admin/knowledge/documents';
};

export type IngestErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type IngestError = IngestErrors[keyof IngestErrors];

export type IngestResponses = {
    /**
     * OK
     */
    200: Job;
};

export type IngestResponse = IngestResponses[keyof IngestResponses];

export type ReindexData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/knowledge/documents/{id}/reindex';
};

export type ReindexErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type ReindexError = ReindexErrors[keyof ReindexErrors];

export type ReindexResponses = {
    /**
     * OK
     */
    200: Job;
};

export type ReindexResponse = ReindexResponses[keyof ReindexResponses];

export type StartImportData = {
    body: CatalogImportRequest;
    headers?: {
        /**
         * Ключ идемпотентности повторной отправки
         */
        'Idempotency-Key'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/admin/catalog/imports';
};

export type StartImportErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type StartImportError = StartImportErrors[keyof StartImportErrors];

export type StartImportResponses = {
    /**
     * Задание принято
     */
    202: ImportJobResponse;
};

export type StartImportResponse = StartImportResponses[keyof StartImportResponses];

export type GetDialogueData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/conversations/{id}/state';
};

export type GetDialogueErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type GetDialogueError = GetDialogueErrors[keyof GetDialogueErrors];

export type GetDialogueResponses = {
    /**
     * OK
     */
    200: DialogueState;
};

export type GetDialogueResponse = GetDialogueResponses[keyof GetDialogueResponses];

export type UpdateDialogueData = {
    body: UpdateDialogue;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/conversations/{id}/state';
};

export type UpdateDialogueErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type UpdateDialogueError = UpdateDialogueErrors[keyof UpdateDialogueErrors];

export type UpdateDialogueResponses = {
    /**
     * OK
     */
    200: DialogueState;
};

export type UpdateDialogueResponse = UpdateDialogueResponses[keyof UpdateDialogueResponses];

export type UpdateData = {
    body: UpdateOffer;
    path: {
        article: string;
        warehouse: string;
    };
    query?: never;
    url: '/api/admin/catalog/offers/{article}/{warehouse}';
};

export type UpdateErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type UpdateError = UpdateErrors[keyof UpdateErrors];

export type UpdateResponses = {
    /**
     * OK
     */
    200: Array<Quote>;
};

export type UpdateResponse = UpdateResponses[keyof UpdateResponses];

export type SourceData = {
    body?: never;
    path: {
        id: string;
        versionId: string;
    };
    query?: never;
    url: '/api/sources/{id}/versions/{versionId}';
};

export type SourceErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type SourceError = SourceErrors[keyof SourceErrors];

export type SourceResponses = {
    /**
     * OK
     */
    200: string;
};

export type SourceResponse = SourceResponses[keyof SourceResponses];

export type GetRunData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/runs/{id}';
};

export type GetRunErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type GetRunError = GetRunErrors[keyof GetRunErrors];

export type GetRunResponses = {
    /**
     * OK
     */
    200: RunSnapshot;
};

export type GetRunResponse = GetRunResponses[keyof GetRunResponses];

export type GetModelUsageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/runs/{id}/usage';
};

export type GetModelUsageErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type GetModelUsageError = GetModelUsageErrors[keyof GetModelUsageErrors];

export type GetModelUsageResponses = {
    /**
     * OK
     */
    200: Array<Usage>;
};

export type GetModelUsageResponse = GetModelUsageResponses[keyof GetModelUsageResponses];

export type StreamRunData = {
    body?: never;
    headers?: {
        'Last-Event-ID'?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/runs/{id}/events';
};

export type StreamRunErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type StreamRunError = StreamRunErrors[keyof StreamRunErrors];

export type StreamRunResponses = {
    /**
     * OK
     */
    200: ChatEvent;
};

export type StreamRunResponse = StreamRunResponses[keyof StreamRunResponses];

export type ByArticleData = {
    body?: never;
    path: {
        article: string;
    };
    query?: never;
    url: '/api/products/{article}';
};

export type ByArticleErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type ByArticleError = ByArticleErrors[keyof ByArticleErrors];

export type ByArticleResponses = {
    /**
     * Карточка товара
     */
    200: ProductResponse;
};

export type ByArticleResponse = ByArticleResponses[keyof ByArticleResponses];

export type QuotesData = {
    body?: never;
    path: {
        article: string;
    };
    query?: never;
    url: '/api/products/{article}/offers';
};

export type QuotesErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type QuotesError = QuotesErrors[keyof QuotesErrors];

export type QuotesResponses = {
    /**
     * OK
     */
    200: Array<Quote>;
};

export type QuotesResponse = QuotesResponses[keyof QuotesResponses];

export type CertificateData = {
    body?: never;
    path: {
        article: string;
        certificateId: string;
    };
    query?: never;
    url: '/api/products/{article}/certificates/{certificateId}';
};

export type CertificateErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type CertificateError = CertificateErrors[keyof CertificateErrors];

export type CertificateResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type CertificateResponse2 = CertificateResponses[keyof CertificateResponses];

export type AnalogsData = {
    body?: never;
    path: {
        article: string;
    };
    query: {
        quantity: string;
        unit?: string;
    };
    url: '/api/products/{article}/analogs';
};

export type AnalogsErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type AnalogsError = AnalogsErrors[keyof AnalogsErrors];

export type AnalogsResponses = {
    /**
     * OK
     */
    200: Result;
};

export type AnalogsResponse = AnalogsResponses[keyof AnalogsResponses];

export type Search2Data = {
    body?: never;
    path?: never;
    query: {
        q: string;
        limit?: number;
        category?: string;
        brand?: string;
        minPrice?: number;
        maxPrice?: number;
    };
    url: '/api/products/search';
};

export type Search2Errors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type Search2Error = Search2Errors[keyof Search2Errors];

export type Search2Responses = {
    /**
     * Результаты поиска
     */
    200: ProductSearchResponse;
};

export type Search2Response = Search2Responses[keyof Search2Responses];

export type PingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ping';
};

export type PingErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type PingError = PingErrors[keyof PingErrors];

export type PingResponses = {
    /**
     * OK
     */
    200: PingResponse;
};

export type PingResponse2 = PingResponses[keyof PingResponses];

export type Search3Data = {
    body?: never;
    path?: never;
    query: {
        query: string;
        characterBudget?: number;
    };
    url: '/api/knowledge/search';
};

export type Search3Errors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type Search3Error = Search3Errors[keyof Search3Errors];

export type Search3Responses = {
    /**
     * OK
     */
    200: KnowledgeSearchResult;
};

export type Search3Response = Search3Responses[keyof Search3Responses];

export type GetResultSetData = {
    body?: never;
    path: {
        id: string;
        resultId: string;
    };
    query?: never;
    url: '/api/conversations/{id}/results/{resultId}';
};

export type GetResultSetErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type GetResultSetError = GetResultSetErrors[keyof GetResultSetErrors];

export type GetResultSetResponses = {
    /**
     * OK
     */
    200: ProductResultSet;
};

export type GetResultSetResponse = GetResultSetResponses[keyof GetResultSetResponses];

export type ResultData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/catalog/results/{id}';
};

export type ResultErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type ResultError = ResultErrors[keyof ResultErrors];

export type ResultResponses = {
    /**
     * OK
     */
    200: SavedSearch;
};

export type ResultResponse = ResultResponses[keyof ResultResponses];

export type OptionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/catalog/options/{id}';
};

export type OptionErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type OptionError = OptionErrors[keyof OptionErrors];

export type OptionResponses = {
    /**
     * OK
     */
    200: Option;
};

export type OptionResponse = OptionResponses[keyof OptionResponses];

export type GetCartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/cart';
};

export type GetCartErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type GetCartError = GetCartErrors[keyof GetCartErrors];

export type GetCartResponses = {
    /**
     * OK
     */
    200: CartSnapshot;
};

export type GetCartResponse = GetCartResponses[keyof GetCartResponses];

export type GetProposalData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/cart/proposals/{id}';
};

export type GetProposalErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type GetProposalError = GetProposalErrors[keyof GetProposalErrors];

export type GetProposalResponses = {
    /**
     * OK
     */
    200: ProposalSnapshot;
};

export type GetProposalResponse = GetProposalResponses[keyof GetProposalResponses];

export type GetCartOperationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/cart/operations/{id}';
};

export type GetCartOperationErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type GetCartOperationError = GetCartOperationErrors[keyof GetCartOperationErrors];

export type GetCartOperationResponses = {
    /**
     * OK
     */
    200: OperationOutcome;
};

export type GetCartOperationResponse = GetCartOperationResponses[keyof GetCartOperationResponses];

export type DeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/attachments/{id}';
};

export type DeleteErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type DeleteError = DeleteErrors[keyof DeleteErrors];

export type DeleteResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteResponse = DeleteResponses[keyof DeleteResponses];

export type StatusData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/attachments/{id}';
};

export type StatusErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type StatusError = StatusErrors[keyof StatusErrors];

export type StatusResponses = {
    /**
     * OK
     */
    200: Snapshot;
};

export type StatusResponse = StatusResponses[keyof StatusResponses];

export type Source1Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/attachments/{id}/source';
};

export type Source1Errors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type Source1Error = Source1Errors[keyof Source1Errors];

export type Source1Responses = {
    /**
     * OK
     */
    200: string;
};

export type Source1Response = Source1Responses[keyof Source1Responses];

export type CapabilitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/attachments/capabilities';
};

export type CapabilitiesErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type CapabilitiesError = CapabilitiesErrors[keyof CapabilitiesErrors];

export type CapabilitiesResponses = {
    /**
     * OK
     */
    200: Capabilities;
};

export type CapabilitiesResponse = CapabilitiesResponses[keyof CapabilitiesResponses];

export type JobData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/knowledge/jobs/{id}';
};

export type JobErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type JobError = JobErrors[keyof JobErrors];

export type JobResponses = {
    /**
     * OK
     */
    200: Job;
};

export type JobResponse = JobResponses[keyof JobResponses];

export type JobStatusData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/admin/jobs/{id}';
};

export type JobStatusErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type JobStatusError = JobStatusErrors[keyof JobStatusErrors];

export type JobStatusResponses = {
    /**
     * Состояние задания
     */
    200: ImportJobResponse;
};

export type JobStatusResponse = JobStatusResponses[keyof JobStatusResponses];

export type RevokeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/knowledge/documents/{id}';
};

export type RevokeErrors = {
    /**
     * Domain error with stable code
     */
    400: ApiProblem;
    /**
     * Domain error with stable code
     */
    401: ApiProblem;
    /**
     * Domain error with stable code
     */
    403: ApiProblem;
    /**
     * Domain error with stable code
     */
    404: ApiProblem;
    /**
     * Domain error with stable code
     */
    409: ApiProblem;
    /**
     * Domain error with stable code
     */
    429: ApiProblem;
    /**
     * Domain error with stable code
     */
    503: ApiProblem;
};

export type RevokeError = RevokeErrors[keyof RevokeErrors];

export type RevokeResponses = {
    /**
     * OK
     */
    200: unknown;
};
