// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8080' | (string & {});
};

export type PingResponse = {
    app?: string;
    status?: string;
    time?: string;
};

export type PingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ping';
};

export type PingResponses = {
    /**
     * OK
     */
    200: PingResponse;
};

export type PingResponse2 = PingResponses[keyof PingResponses];
